# Render.com deployment configuration
# BDE Sales Document Portal - Clean v2 Architecture

services:
  - type: web
    name: bde-sales-document-portal
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    
    envVars:
      # Application
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 10000
      
      # Database (will be set automatically by Render)
      - key: DATABASE_URL
        fromDatabase:
          name: sales-portal-production
          property: connectionString
      
      # DocuSeal Integration
      - key: DOCUSEAL_URL
        value: https://bde-docuseal-service.onrender.com
      - key: DOCUSEAL_API_TOKEN
        sync: false  # Set manually after DocuSeal deployment
      
      # Email Configuration
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USERNAME
        value: transaction.coordinator.agent@gmail.com
      - key: SMTP_PASSWORD
        value: xmvi xvso zblo oewe
      - key: FROM_EMAIL
        value: transaction.coordinator.agent@gmail.com
      
      # Security
      - key: SECRET_KEY
        generateValue: true
      
      # Application URLs
      - key: BASE_URL
        value: https://bde-sales-document-portal.onrender.com
      - key: WEBHOOK_BASE_URL
        value: https://bde-sales-document-portal.onrender.com/api/v1/webhooks

  # DocuSeal Service - Deploy separately later

databases:
  # Main application database
  - name: sales-portal-production
    databaseName: sales_portal_production
    user: portal_user
    plan: free
  
  # DocuSeal database - Create separately later